import type { Metadata } from "next";
import { Inter, DM_Serif_Display, Arvo, Aleo, Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800"] });
const arvo = Arvo({ subsets: ["latin"], weight: ["400"] });
const smserif = DM_Serif_Display({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
